const STORE = [
    {
        text: `1. Where was modern pizza invented?`,
        a: `New York City, USA`,
        b: `Naples, Italy`,
        c: `Sicily, Italy`,
        d: `Florence, Italy`,
        answer: `Naples, Italy`,
    },
    {
        text: `2. Who invented the pizza Margherita for visiting Queen Margherita?`,
        a: `Raffaele Esposito`,
        b: `Mario Batali`,
        c: `Enrique Iglesias`,
        d: `Michelangelo`,
        answer: `Raffaele Esposito`,
    },
    {
        text: `3. What is a pizza maker called in Italian?`,
        a: `Bobbita Flaya`,
        b: `Pizzaiolo`,
        c: `Pize`,
        d: `Papa John`,
        answer: `Pizzaiolo`,
    },
    {
        text: `4. What do the green, red, and white pizza Marghertia colors represent?`,
        a: `Nature, Love, & the Pope`,
        b: `Spring, Passion, Purity`,
        c: `Colors of the Italian flag`,
        d: `Colors of Queen Marghertia’s dress`,
        answer: `Colors of the Italian flag`,
    },
    {
        text: `5. When was the modern pizza invented?`,
        a: `Early 1900`,
        b: `500 BCE`,
        c: `1980’s`,
        d: `1970’s`,
        answer: `Early 1900`,
    },
    {
        text: `6. How many pizzerias are in the United States?`,
        a: `300`,
        b: `1,200`,
        c: `61,000`,
        d: `1,000,000`,
        answer: `61,000`,
    },
    {
        text: `7. What are the common pizza dough ingredients?`,
        a: `00 Wheat Flour, yeast, water`,
        b: `Milk, eggs, Chickpea Flour`,
        c: `Milk, Wheat Flour, Baking Soda`,
        d: `Wheat Flour, Salt, Water`,
        answer: `00 Wheat Flour, yeast, water`,
    },
    {
        text: `8. What is the traditional way of cooking a pizza?`,
        a: `Microwave`,
        b: `Stove-top`,
        c: `Over a fire`,
        d: `Wood-Fired Oven`,
        answer: `Wood-Fired Oven`,
    },
    {
        text: `9. What is Chicago style pizza called?`,
        a: `Deep Dish`,
        b: `Shallow dish`,
        c: `Flatbread`,
        d: `Too saucy by experts`,
        answer: `Deep Dish`,
    },
    {
        text: `10. How do you eat a New York style slice?`,
        a: `Fork and Knife`,
        b: `Folded down the center`,
        c: `Only sitting down in a restaurant`,
        d: `Before Noon`,
        answer: `Folded down the center`,
    }
]

const ANSWERS = [ 
    `Naples, Italy`,
    `Raffaele Esposito`,
    `Pizzaiolo`,
    `Colors of the Italian flag`,
    `Early 1900's`,
    `61,000`,
    `00 Wheat Flour, yeast, water`,
    `Wood-Fired Oven`,
    `Deep Dish`,
    `Folded down the center`,
  ];
  